#!/bin/bash
set -e
#set -x

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

PACKAGE="mce-roundcube"
CONFSCRIPT="/usr/share/mce-roundcube/scripts/configure.sh"

# colors
	GREEN='\033[0;32m'
	RED='\033[1;31m'
	YELLOW='\033[0;33m'
	BLUE='\033[1;34m'
	NC='\033[0m' # No Color

echo -e " ${GREEN} initial configuration${NC}"
is_initial_configuration() {
# Check if this is the initial configuration and not an upgrade of an
# existing configuration
# Usage: if is_initial_configuration "$@"; then ... fi from top level

	# Plain installation
	if [ "$1" = configure ] && [ -z "$2" ]; then
	        return 0
	fi
	# Configuration via dpkg-reconfigure
	if [ "$1" = reconfigure ] || [ "$DEBCONF_RECONFIGURE" ]; then
	        return 0
	fi
	return 1
}


#Install

if is_initial_configuration "$@"; then

    if [ "$DEBIAN_FRONTEND" != "noninteractive" ] ; then
        # Fetching configuration from debconf

        RCHOSTNAME="localhost"

        db_get $PACKAGE/confType
        CONFTYPE=$RET

        if [ "$CONFTYPE" == *"Postgres"* ] ; then
            db_get $PACKAGE/rchostname
            RCHOSTNAME="$RET"

        fi

	M2HOSTNAME=""
        M2DBNAME=""
        M2DBUSE=""
        M2DBPW=""

        RCDBNAME=""
        RCDBUSER=""
        RCDBPW=""

	LDAPHOSTNAME=""

# get conf RC
                db_get  $PACKAGE/rcdbname || true
                RCDBNAME=$RET

                db_get  $PACKAGE/rcdbuser || true
                RCDBUSER=$RET

                db_get  $PACKAGE/rcdbpw || true
                RCDBPW=$RET

# get conf m2
                db_get  $PACKAGE/m2hostname || true
                M2HOSTNAME=$RET

		db_get  $PACKAGE/m2dbname || true
		M2DBNAME=$RET

                db_get  $PACKAGE/m2dbuser || true
                M2DBUSER=$RET

                db_get  $PACKAGE/m2dbpw || true
                M2DBPW=$RET

#get conf LDAP
                db_get  $PACKAGE/ldaphostname || true
                LDAPHOSTNAME=$RET



        /bin/bash  $CONFSCRIPT -s "$RCHOSTNAME" -d "$RCDBNAME" -u "$RCDBUSER" -w "$RCDBPW" -S "$M2HOSTNAME" -D "$M2DBNAME" -u "$M2DBUSER" -W "$M2DBPW" -l "$LDAPHOSTNAME"

    else
        echo "You have, now, to launch $CONFSCRIPT  script for configuring Postfix"

    fi

fi

exit 0





